import React, { useState, useEffect } from 'react';
import { Filter, Clock, Activity, Plus } from 'lucide-react';
import API from '../api'; 

const RecommendationsView = ({ isDarkMode, user }) => {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showAddSkill, setShowAddSkill] = useState(false);
  const [newSkill, setNewSkill] = useState({ name: '', level: 80 });

  // 1. Fetch Recommendations from Backend (Database)
  const fetchRecs = async () => {
    if (!user?._id) return;
    try {
      setLoading(true);
      // This calls the backend controller which returns "Default" cards OR "Matched" cards
      const { data } = await API.get(`/recommendations/${user._id}`);
      setRecommendations(data);
    } catch (error) {
      console.error("Failed to fetch recs", error);
    } finally {
      setLoading(false);
    }
  };

  // 2. Fetch on Component Mount (Initial Load)
  useEffect(() => {
    fetchRecs();
  }, [user]);

  // 3. Handle Adding a Skill (Triggers Database Update & UI Refresh)
  const handleAddSkill = async (e) => {
    e.preventDefault();
    try {
      // Add skill to User's target list in DB
      await API.post(`/users/${user._id}/skills`, {
        skillName: newSkill.name,
        level: newSkill.level,
        type: 'target'
      });

      // Clear Form
      setShowAddSkill(false);
      setNewSkill({ name: '', level: 80 });

      // RE-FETCH to get the new recommendations generated by the backend
      await fetchRecs();
      
    } catch (error) {
      alert("Error adding skill");
    }
  };

  // Helper for Styles
  const cardClass = isDarkMode ? "bg-gray-800 border-gray-700" : "bg-white border-gray-100";
  const textMain = isDarkMode ? "text-white" : "text-gray-900";
  const textSub = isDarkMode ? "text-gray-400" : "text-gray-500";
  const inputClass = `w-full p-2 rounded border ${isDarkMode ? 'bg-gray-700 border-gray-600 text-white' : 'bg-white border-gray-300'}`;

  // Helper for Domain Colors (Matches your Seed Data domains)
  const getDomainColor = (domain) => {
    switch (domain) {
      case 'Healthcare': return 'bg-red-100 text-red-700';
      case 'Urban': return 'bg-blue-100 text-blue-700';
      case 'Agriculture': return 'bg-green-100 text-green-700';
      case 'Tech': return 'bg-purple-100 text-purple-700';
      default: return 'bg-gray-100 text-gray-700';
    }
  };

  return (
    <div className="animate-in slide-in-from-right-4 duration-500 pb-10">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-center mb-6 gap-4">
        <div>
          <h2 className={`text-xl font-bold ${textMain}`}>Personalized Recommendations</h2>
          <p className={`text-sm ${textSub}`}>AI-curated opportunities to bridge your skill gaps</p>
        </div>
        
        <div className="flex gap-2">
          <button 
            onClick={() => setShowAddSkill(!showAddSkill)}
            className="flex items-center text-sm font-medium px-4 py-2 rounded-lg bg-blue-600 text-white hover:bg-blue-700 transition-colors shadow-sm"
          >
            <Plus size={16} className="mr-2"/> Add Target Skill
          </button>
          <button className={`flex items-center text-sm font-medium px-3 py-2 rounded-lg border transition-colors ${isDarkMode ? 'bg-gray-800 border-gray-700 text-gray-300 hover:bg-gray-700' : 'bg-white border-gray-200 text-gray-600 hover:bg-gray-50'}`}>
            <Filter size={16} className="mr-2"/> Filter
          </button>
        </div>
      </div>

      {/* Add Skill Form */}
      {showAddSkill && (
        <form onSubmit={handleAddSkill} className={`mb-6 p-4 rounded-xl border shadow-sm flex flex-col md:flex-row gap-4 items-end animate-in fade-in slide-in-from-top-2 ${cardClass}`}>
          <div className="flex-1 w-full">
            <label className={`block text-xs font-bold mb-1 ${textSub}`}>Skill to Improve</label>
            <input 
              type="text" 
              placeholder="e.g. R Programming" 
              className={inputClass}
              value={newSkill.name}
              onChange={(e) => setNewSkill({...newSkill, name: e.target.value})}
              required
            />
          </div>
          <div className="w-full md:w-32">
            <label className={`block text-xs font-bold mb-1 ${textSub}`}>Target Level (%)</label>
            <input 
              type="number" 
              className={inputClass}
              value={newSkill.level}
              onChange={(e) => setNewSkill({...newSkill, level: e.target.value})}
            />
          </div>
          <button type="submit" className="w-full md:w-auto bg-green-600 text-white px-6 py-2 rounded-lg font-bold hover:bg-green-700 transition-colors">
            Save & Update
          </button>
        </form>
      )}

      {/* Recommendations Grid */}
      {loading ? (
        <div className={`text-center py-10 ${textSub}`}>Loading from database...</div>
      ) : recommendations.length === 0 ? (
        <div className={`text-center py-10 ${textSub}`}>
          No recommendations found. Try adding a different skill or checking your database seed.
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {recommendations.map((rec) => (
            <div key={rec._id} className={`${cardClass} rounded-xl shadow-sm border p-5 flex flex-col hover:shadow-md transition-shadow`}>
              {/* Card Header */}
              <div className="flex justify-between items-start mb-3">
                 <span className={`text-[10px] font-bold px-2 py-1 rounded-full ${getDomainColor(rec.domain)}`}>
                     {rec.domain}
                </span>
                <span className={`text-xs px-2 py-1 rounded border font-medium ${isDarkMode ? 'border-gray-600 bg-gray-700' : 'border-orange-100 bg-orange-50 text-orange-700'}`}>
                  {rec.type}
                </span>
              </div>
              
              {/* Card Title */}
              <h3 className={`text-lg font-bold mb-2 leading-tight ${textMain}`}>{rec.title}</h3>
              <p className={`text-sm mb-4 flex-1 ${textSub}`}>{rec.provider}</p>
              
              {/* Metadata */}
              <div className={`flex items-center gap-4 text-xs mb-4 ${textSub}`}>
                <span className="flex items-center"><Clock size={14} className="mr-1"/> {rec.duration}</span>
                <span className="flex items-center"><Activity size={14} className="mr-1"/> {rec.difficulty}</span>
              </div>
              
              {/* Footer */}
              <div className={`pt-4 border-t mt-auto ${isDarkMode ? 'border-gray-700' : 'border-gray-100'}`}>
                <div className="flex justify-between items-center mb-3">
                  <span className={`text-xs font-medium ${textSub}`}>Skill Impact</span>
                  <div className="flex items-center text-xs font-bold text-green-600">
                     {rec.impact}
                  </div>
                </div>
                <button className={`w-full py-2 font-bold rounded-lg text-sm transition-colors ${isDarkMode ? 'bg-blue-900/40 text-blue-400 hover:bg-blue-900/60' : 'bg-blue-50 text-blue-600 hover:bg-blue-100'}`}>
                  Start Now
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default RecommendationsView;